import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Appbar from '@/components/menu/Navbar'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <Appbar />
        <main className="mx-auto mt-8 w-4/5">{children}</main>
      </body>
    </html>
  )
}
