import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Appbar from '@/components/menu/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Appbar />
        <main className="mx-auto mt-8 w-4/5">{children}</main>
      </body>
    </html>
  )
}
